"""Operations modules import shortcut"""
from operations.integer_sum import integer_sum
from operations.multi import multi
from operations.div import div
from operations.hypotenuse import hypotenuse
from operations.deg_to_rad import deg_to_rad
from operations.inch_to_cent import inch_to_cent
from operations.pound_to_kilos import pound_to_kilos
from operations.farkel_to_cel import farkel_to_cel
